# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
