# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
